- name: Configuring MongoDB Repository
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing MongoDB 
  ansible.builtin.package:
    name: mongodb-org
    state: present  

- name: Updating the MongoDB Config to be public
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0' 

- name: Starting MongoDB 
  ansible.builtin.systemd:
    name: mongod 
    state: started
    enabled: true 

- name: Download and extract Mongodb Schema
  ansible.builtin.include_role:
    name: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp 
    remote_src: yes 

- name: Injecting the MongoDB catalogue Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/{{COMPONENT}}-main/catalogue.js"
    idempotent: yes 

- name: Injecting the MongoDB user Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/{{COMPONENT}}-main/user.js"
    idempotent: yes 
