- name: Demo on using variables on playbooks 
  hosts: all
  vars:
    URL: play.google.com

  tasks: 
    - name: Printing value of the variable 
      ansible.builtin.debug:
        msg: value of URL is {{ URL }}

    - name: Printing Hai From Play1
      ansible.builtin.debug:
        msg: Hai from play1 of task2
